trigger:
  branches:
    include:
    - '*'

stages:
- stage: test
  jobs:

  - job: macos
    pool:
      vmImage: 'macOS-12'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
        Python310:
          python.version: '3.10'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'
    - template: .azure-pipelines/build-run-tests.yml

- stage: build_wheels
  jobs:
  - job: macos
    pool:
      vmImage: 'macOS-12'
    steps:
      - task: UsePythonVersion@0
      - bash: |
          set -o errexit
          python3 -m pip install --upgrade pip
          python3 -m pip install cibuildwheel==2.8.0
        displayName: Install cibuildwheel dependencies
      - bash: cibuildwheel --output-dir wheelhouse .
        env:
          CIBW_BUILD_VERBOSITY: 3
          CIBW_SKIP: "cp36-*"
          CIBW_ARCHS_MACOS: x86_64 universal2
        displayName: Build wheels
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: wheelhouse
          artifactName: wheels
